### ISSUE TITLE
Setting GoRouter

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_CLIENT#2]
# 🍅  TO-DOs
- [ ] Go Router Constant 페이지 설정
- [x] 에러 핸들러 작성
- [ ] 관련 공식문서 읽고 정리

# 📚  Details
- Material UI에서 제공하는 라우터를 사용하려 했으나 프로젝트 사이즈에 알맞지 않음
- 추가 library를 사용하여 라우팅 설정 필요

# 🧊  관련 이슈
#1
