### ISSUE TITLE
[UI] 레시피 화면

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_CLIENT#4]
# 🍅 TO-DOs
- [ ] 레시피 반환 카드 뷰
- [ ] 레시피 종류별 분류 divider
- [ ] 레시피 카드 클릭 시 이동

# 📚 Details
- 레시피를 조회할 수 있는 화면의 UI를 구성합니다.

# 🧊 관련 이슈
