### ISSUE TITLE
[Feature] 메인 네비게이션 바 모달창 구성

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_CLIENT#5]
# 🍅 TO-DOs
- [x] 모달 UI 커스텀
- [x] 모달 버튼 1: 사진 촬영 화면으로 이동
- [x] 모달 버튼 2: 수동 식재료 입력 화면으로 이동

# 📚 Details
- 

# 🧊 관련 이슈
