### ISSUE TITLE
[Feature] 수동 상품 추가 기능

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_CLIENT#7]
# 🍅 TO-DOs
- [x] 화면 구성: Appbar, ListView, Bottom Modal, Modal Button
- [x] '식재료 추가' 버튼 클릭 시 모달창
- [x] 모달창 위젯 배치
- [x] 모달창에서 식재료 추가
- [x] Provider 구성 및 등록
- [x] 식재료 추가 시 ListView에서 확인 가능
- [x] '식재료 등록' 버튼 클릭 시 콘솔에서 식재료 리스트 출력 확인(후에 https 요청으로 변경)

# 📚 Details
- 바텀 네비게이션 바 의 모달창에서 수동 상품 추가 기능 페이지로 들어갔을 때, 상품을 추가할 수 있는 기능
- 리스트 형식으로 구현
- Provider 라이브러리 사용
-  ~2/14 화요일

# 🧊 관련 이슈
